### ISSUE TITLE
Deno Fresh 1.1.1 TypeError in BarChartContainer example

### ISSUE THREAD

**Issue by robvanvolt** [oslabs-beta/d3no-data#64]
**Describe the bug**
Default example of webpage does not work with Deno Fresh 1.1.1:

`error: Uncaught (in promise) TypeError: pragma cannot be set when runtime is automatic at https://deno.land/x/d3nodata@v.0.1.1/chart-comps/BarChart.tsx:1:1
  await import(entrypoint);
  ^
    at async dev (https://deno.land/x/fresh@1.1.1/src/dev/mod.ts:187:3)
    at async file:///Users/robert/Developer/deno/survey/dev.ts:7:1
Watcher Process finished. Restarting on file change...`

**To Reproduce**
1. Create Deno Fresh App v1.1.1
2. Insert island and code as in the github readme of d3no-data
3. deno task start

**Expected behavior**
A graph should be displayed.

**Desktop (please complete the following information):**
 - OS: MacOS M1 pro
 - Browser Firefox

**Comment by aw1ld3v13** [comment]
Thanks for reporting the issue! Working on this now to fix ASAP. Will close the issue once the latest release actually fixes the issue - it's proven a bit more complicated to fix than I initially expected.
